# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{first_github_commit}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christoph Olszowka"]
  s.date = %q{2010-06-03}
  s.description = %q{Find the first commit for a given github repository and return the API info for it by traversing the }
  s.email = %q{christoph at olszowka dot de}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "first_github_commit.gemspec",
     "lib/first_github_commit.rb",
     "test/fast_context.rb",
     "test/helper.rb",
     "test/ruby_ext.rb",
     "test/test_first_github_commit.rb"
  ]
  s.homepage = %q{http://github.com/colszowka/first_github_commit}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Find the first commit for a given github repository and return the API info for it}
  s.test_files = [
    "test/fast_context.rb",
     "test/helper.rb",
     "test/ruby_ext.rb",
     "test/test_first_github_commit.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<redirect_follower>, [">= 0.1.1"])
      s.add_development_dependency(%q<shoulda>, [">= 2.10.2"])
    else
      s.add_dependency(%q<redirect_follower>, [">= 0.1.1"])
      s.add_dependency(%q<shoulda>, [">= 2.10.2"])
    end
  else
    s.add_dependency(%q<redirect_follower>, [">= 0.1.1"])
    s.add_dependency(%q<shoulda>, [">= 2.10.2"])
  end
end

